---
apiVersion: v2
appVersion: v1
description: Automatically sync TRaSH guides to your Sonarr and Radarr instances. 
name: recyclarr
version: 4.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - sonarr
  - radarr
  - recyclarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/incubator/recyclarr
icon: https://github.com/Sonarr/Sonarr/blob/phantom-develop/Logo/512.png?raw=true
sources:
  - https://hub.docker.com/r/recyclarr/recyclarr
  - https://github.com/recyclarr/recyclarr
maintainers:
  - name: pyaniz
    email: pyaniz@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
